### PR TITLE
Handle all server errors. Fixes #182

### LINKED ISSUE #182: unexpected_message
Hello. I keep getting this error (rarely, once in a month):
{unexpected_message,69,epgsql_cmd_connect,...} because epgsql_cmd_connect:handle_message/4 receives {error,важно, <<"53300">>, too_many_connections, <<"оставшиеся слоты подключений зарезервированы для подключений суперпользователя (не для репликации)">>,
                                                         [{file,<<"src\\backend\\utils\\init\\postinit.c">>},
                                                          {line,<<"718">>},
                                                          {routine, <<"InitPostgres">>}]}, 
but Stage is 'initialization' instead of 'auth' or 'maybe_auth'.

Also in this file 'auth_state' can be 'undefned' instead of 'undefined'.

### PR DESCRIPTION
**Pull request by seriyps**
Fix for #182.
Adds handling for all server-side errors in any state.

### CODE REVIEW

File: test/epgsql_SUITE.erl [hunk 1]
```diff
@@ -41,6 +41,8 @@ groups() ->
             connect_with_scram,
             connect_with_invalid_user,
             connect_with_invalid_password,
+            connect_to_invalid_database,
+            connect_with_oter_error,
```
Comment (grahamrhay) [inline test/epgsql_SUITE.erl]: other?

Comment (seriyps) [reply test/epgsql_SUITE.erl]: true! fixed and force-pushed
